"""
DAG generated by Dagitron from simple_pipeline.yaml

This file was automatically generated. Do not edit manually.
To make changes, modify the source YAML file and regenerate.
"""

from dagitron import generate_dag_from_yaml
import os

# Path to the YAML specification file
YAML_FILE = "/home/runner/work/dagitron/dagitron/examples/simple_pipeline.yaml"

# Generate the DAG from YAML
if os.path.exists(YAML_FILE):
    dag = generate_dag_from_yaml(YAML_FILE)
    
    # Make the DAG available to Airflow
    globals()["simple_pipeline"] = dag
else:
    # Fallback if YAML file is not found
    from airflow import DAG
    from airflow.operators.dummy import DummyOperator
    from datetime import datetime
    
    dag = DAG(
        "simple_pipeline",
        description="Generated DAG (YAML file not found)",
        schedule_interval=None,
        start_date=datetime(2024, 1, 1),
        catchup=False,
    )
    
    dummy_task = DummyOperator(
        task_id="yaml_file_not_found",
        dag=dag,
    )
    
    globals()["simple_pipeline"] = dag